name: todoapp

services:
  frontend:
    build: ./frontend/
    ports: [ "${FRONTEND_PORT}:80" ]
    environment:
      BACKEND_URL: "http://localhost:${BACKEND_PORT}"

  backend:
    build: ./backend/
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      DATABASE_USERNAME: todouser
      DATABASE_PASSWORD: ${DB_PASS}
      DATABASE_HOST: db
      DATABASE_NAME: todo_db
      JWT_SECRET_KEY: ${SECERT_KEY}
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_USER: "todouser"
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: todo_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my_network

volumes:
  db-data:


networks:
  my_network:
